"""empty message

Revision ID: 13ca6ea0e8bb
Revises: 
Create Date: 2017-02-17 05:19:05.120866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ca6ea0e8bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_description', sa.String(), nullable=False),
    sa.Column('store_owner', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_owner'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['stores.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_store_owner_email'), 'store_owner', ['email'], unique=True)
    op.create_index(op.f('ix_store_owner_first_name'), 'store_owner', ['first_name'], unique=False)
    op.create_index(op.f('ix_store_owner_last_name'), 'store_owner', ['last_name'], unique=False)
    op.create_index(op.f('ix_store_owner_username'), 'store_owner', ['username'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('product_description', sa.String(), nullable=False),
    sa.Column('store_home', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['store_home'], ['store.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_index(op.f('ix_store_owner_username'), table_name='store_owner')
    op.drop_index(op.f('ix_store_owner_last_name'), table_name='store_owner')
    op.drop_index(op.f('ix_store_owner_first_name'), table_name='store_owner')
    op.drop_index(op.f('ix_store_owner_email'), table_name='store_owner')
    op.drop_table('store_owner')
    op.drop_table('store')
    op.drop_table('users')
    op.drop_table('stores')
    op.drop_table('roles')
    ### end Alembic commands ###
